export const fakeBusinessNames = [
  "Stellar Solutions Inc.",
  "Envision Consulting Group",
  "Summit Ventures LLC",
  "BlueSky Innovations",
  "BrightPath Enterprises",
  "Dynamic Directions Inc.",
  "Proven Progress LLC",
  "Redwood Partners",
  "Top Tier Technologies",
  "NextWave Industries",
  "Visionary Ventures Inc.",
  "Boldly Better Business",
  "Elite Innovations LLC",
  "Future Foresight Group",
  "Precision Partners Inc.",
  "Quantum Quest LLC",
  "Stellar Strategies",
  "Apex Advancement Group",
  "Ignite Ideas LLC",
  "Thrive Consulting Co.",
  "Horizon Holdings Inc.",
  "Optimum Outcomes Group",
  "Fortitude Funding Co.",
  "Bluebird Brands",
  "Silver Summit Solutions",
  "Nimbus Networks Inc.",
  "Inception Industries",
  "Titan Technologies",
  "Vertex Ventures",
  "Progress Partners LLC",
  "Catalyst Consulting Group",
  "Inspired Intelligence Inc.",
  "Phoenix Partnerships",
  "Inflection Point Solutions",
  "Pinnacle Performance Group",
  "Prime Progression Partners",
  "Eclipse Enterprises Inc.",
  "NextGen Innovations LLC",
  "Synergy Solutions Group",
  "Precision Progress Inc.",
  "Forward Foresight Inc.",
  "Fortitude Frontiers",
  "Redwood Resources",
  "Future Focus Firm",
  "Beyond Boundaries Enterprises",
  "Bright Bridge Business",
  "Stellar Startups",
  "Envision Endurance",
  "Elite Enterprises LLC",
  "Visionary Ventures Co.",
  "Summit Solutions Group",
  "Dynamic Development Inc.",
  "Proven Progression Partners",
  "Bright Beginnings LLC",
  "Quantum Quest Consulting",
  "Ignite Innovation Inc.",
  "Thrive Together Partners",
  "Horizon Holdings LLC",
  "Optimum Outcomes Consulting",
  "Fortitude Finance Co.",
  "Bluebird Business Solutions",
  "Silver Summit Strategies",
  "Nimbus Network Solutions",
  "Inception Innovations",
  "Titan Transformation Co.",
  "Vertex Ventures Group",
  "Progress Progression Partners",
  "Inspired Ideals LLC",
  "Phoenix Performance Partners",
  "Inflection Point Progression",
  "Pinnacle Performance Solutions",
  "Prime Progression LLC",
  "Acme Inc.",
  "Apex Enterprises",
  "Atlas Corp.",
  "Axis Industries",
  "Blue Sky Corporation",
  "BrightStar Corporation",
  "Capital Ventures",
  "Castle Holdings",
  "Catalyst Co.",
  "Clear Vision Corporation",
  "Coastline Industries",
  "Crown Corporation",
  "Delta Group",
  "Discovery Corporation",
  "Eclipse Enterprises",
  "Elite Holdings",
  "Envision Corporation",
  "Everest Enterprises",
  "Expanse Corporation",
  "Falcon Enterprises",
  "Firefly Corporation",
  "Galaxy Holdings",
  "Global Ventures",
  "Golden Horizon Corporation",
  "Grand Holdings",
  "Greenway Corporation",
  "Horizon Corporation",
  "Infinity Corporation",
  "Intrepid Enterprises",
  "Journey Corporation",
  "Legacy Corporation",
  "Liberty Corporation",
  "Majestic Corporation",
  "Momentum Corporation",
  "New Horizons Corporation",
  "Noble Corporation",
  "Odyssey Enterprises",
  "Onyx Corporation",
  "Oracle Corporation",
  "Orion Enterprises",
  "Pacific Holdings",
  "Pathfinder Corporation",
  "Peak Corporation",
  "Phoenix Enterprises",
  "Pioneer Corporation",
  "Platinum Holdings",
  "Polar Corporation",
  "Pristine Corporation",
  "Quest Corporation",
  "Radiant Corporation",
  "Regal Corporation",
  "Refined Corporation",
  "Reliance Corporation",
  "Renaissance Enterprises",
  "Resilience Corporation",
  "Revolution Corporation",
  "Rising Sun Corporation",
  "Royal Corporation",
  "Sapphire Corporation",
  "Silver Star Corporation",
  "Skyline Enterprises",
  "Solar Corporation",
  "Spark Corporation",
  "Spectrum Corporation",
  "Starlight Corporation",
  "Summit Corporation",
  "Sunrise Corporation",
  "Superior Corporation",
  "Swift Corporation",
  "Titan Enterprises",
  "Topaz Corporation",
  "Tranquil Corporation",
  "Trinity Enterprises",
  "Triumph Corporation",
  "Trust Corporation",
  "Unity Corporation",
  "Vanguard Corporation",
  "Velocity Corporation",
  "Venture Corporation",
  "Victory Enterprises",
  "Visionary Corporation",
  "Vista Corporation",
  "Vitality Corporation",
  "Voyager Enterprises",
  "West Coast Corporation",
  "White Oak Corporation",
  "Wildfire Corporation",
  "Willow Corporation",
  "Windward Corporation",
  "Wise Owl Corporation",
  "Worldview Corporation",
  "Xenon Corporation",
  "Xpand Enterprises",
  "Xquisite Corporation",
  "Yellow Brick Corporation",
  "Yellowstone Corporation",
  "Zenith Corporation",
  "Zeus Enterprises",
  "Zest Corporation",
  "Zephyr Corporation",
  "Zinc Corporation",
];
